### ISSUE TITLE
Peerreview

### ISSUE THREAD

**Issue by SimonPlanje** [NathanNeelis/frontend-applications#2]
- Readme en repo ziet er echt top uit! heel overzichtelijk en duidelijk.
- De linkjes in je wiki onder insight, linken nog door naar je frontend-data wiki
- Je zou nog een pagina kunnen toevoegen met waar we het over hebben gehad tijdens de discussie over React en of je na die discussie nog steeds React het beste framework vind om te gebruiken voor je applicatie.  

Dit zijn serieus de enige punten wat ik er even snel uit kan halen. Volgensmij ben je echt al bijna klaar! Ziet er super strak uit. Vind je documentatie van je de features van React heel overzichtelijk. Lekker bezig!! 🤙🤙 
(Sorry, ben ook een beetje laat haha)

**Comment by NathanNeelis** [comment]
Fixed de linkjes  
Pagina is toegevoegd over de discussie van frameworks (was ik al aan het schrijven :) )
Thnx voor de feedback!
